### ISSUE TITLE
Generate checkstyle-like XML report

### ISSUE THREAD

**Issue by scand1sk** [scapegoat-scala/scapegoat#107]
Generating an XML report using the Checkstyle format would be helpful for using Scapegoat with Continuous Integration tools such as Jenkins or Sonar.

**Comment by sksamuel** [comment]
Great idea.

**Comment by RichardBradley** [comment]
[Here's the analogous code](https://github.com/scalastyle/scalastyle/blob/bb276857d5841aa863f66e0aca817fef83fecedd/src/main/scala/org/scalastyle/Output.scala#L133) from `scalastyle`, which outputs its results in "checkstyle" format (which is understood by many CI tools like Jenkins).
