### ISSUE TITLE
How to disable individual rules as scalac compiler plugin

### ISSUE THREAD

**Issue by xanderdunn** [scapegoat-scala/scapegoat#126]
I'm trying to disable the EmptyIfBlock rule.  I'm using scapegoat as a compiler plugin: 

```
scalaCompileOptions.additionalParameters = ["-Xplugin:scalac-scapegoat-plugin_2.11.jar", "-P:scapegoat:dataDir:.", "-P:scapegoat:consoleOutput:true", "-P:scapegoat:disabled:(\"EmptyIfBlock\")"]
```

The `-P:scapegoat:disabled:` parameter is described [here](https://github.com/sksamuel/scalac-scapegoat-plugin/blob/89453a4571e3e14af4962a79c4b43b12b42014f3/src/main/scala/com/sksamuel/scapegoat/plugin.scala), but I'm having trouble with the list syntax.

I've tired `[EmptyIfBlock]`, `Seq(\"EmptyIfBlock\")`, `Seq(EmptyIfBlock)`, `(EmptyIfBlock)`, and `(\"EmptyIfBlock\")` without luck.  I'm still getting the warning: 

```
[warning] ai.osaro.master.FixedPolicyControllerModule.scala:19: Empty if statement
          if (subscriber.isUnsubscribed)
  ()
else
  ()
```

**Comment by shehzadqureshi** [comment]
there's a bug in the description. it should be "-P scapegoat:disabledInspections:" not "-P scapegoat:disabled:"
