### ISSUE TITLE
PredefIterableIsMutable doesn't apply to Scala 2.13.

### ISSUE THREAD

**Issue by mwz** [scapegoat-scala/scapegoat#289]
The `PredefIterableIsMutable` rule no longer applies to Scala 2.13 as `Iterable` now aliases `scala.collection.Iterable` which in turn delegates to `immutable.Iterable`.

The same applies to `PredefSeqIsMutable`.

This rule should be ignored in 2.13.

**Comment by mccartney** [comment]
Similar to #294

**Comment by mwz** [comment]
There is [this](https://github.com/sksamuel/scapegoat/blob/master/src/main/scala/com/sksamuel/scapegoat/package.scala#L7) that we could use.

**Comment by saeltz** [comment]
`PredefSeqIsMutable` is already disabled for Scala 2.13: https://github.com/sksamuel/scapegoat/blob/5c690f685632d4b784fb0a187ef0091ec395a233/src/main/scala/com/sksamuel/scapegoat/inspections/collections/PredefSeqIsMutable.scala#L16
