### ISSUE TITLE
PredefTraversableIsMutable doesn't apply to Scala 2.13

### ISSUE THREAD

**Issue by mwz** [scapegoat-scala/scapegoat#294]
`Traversable` aliases `Iterable` and it's also deprecated now in Scala 2.13, so it should probably be disabled when Scapegoat is run against a 2.13 codebase.

**Comment by mccartney** [comment]
Do we even have support to skip some inspections for some Scala versions?
I guess we need to add that.

**Comment by mccartney** [comment]
Answering myself, we do have support for enabling/disabling inspections per Scala major version, e.g.:
https://github.com/sksamuel/scapegoat/blob/5c690f685632d4b784fb0a187ef0091ec395a233/src/main/scala/com/sksamuel/scapegoat/inspections/collections/PredefSeqIsMutable.scala#L16
