### ISSUE TITLE
PointlessTypeBounds fires on MyClass[T <: AnyRef, S]

### ISSUE THREAD

**Issue by migesok** [scapegoat-scala/scapegoat#415]
I have a piece of code which fires `PointlessTypeBounds`:
```
abstract class BaseSerializer[T <: AnyRef, S](implicit
  toSerTransformer: Transformer[T, S],
  fromSerTransformer: Transformer[S, T],
  codec: JsonValueCodec[S],
  modelClassTag: ClassTag[T],
) extends SerializerWithStringManifest with ByteBufferSerializer {
```
Gives me:
```
[warning] XXX. BaseSerializer.scala:25: Pointless Type Bounds
          Type bound resolves to Nothing <: T <: Any. Did you mean to put in other bounds: type S
```
Strangely enough, the warning goes away when I:
- make S extend AnyRef as well
- put more spaces between `<:` and `AnyRef`

**Comment by migesok** [comment]
Scapegoat version 1.4.5

**Comment by migesok** [comment]
I've checked out the code, I guess this explains why the trick with spaces worked:
```
&& (rhs.pos.lineContent.contains("<: Any")
```

**Comment by mccartney** [comment]
Indeed, the checks we have there are based on textual rendering of some `toStrings`:
https://github.com/sksamuel/scapegoat/blob/5750a81181cfc405914a334e86af87e1577deac0/src/main/scala/com/sksamuel/scapegoat/inspections/inference/PointlessTypeBounds.scala#L27

**Comment by mccartney** [comment]
I think that reproduces the same issue:
```
class Test[T <: AnyRef, S]
```
Our current inspection code:
- checks if the the type has no bounds, it's the case for `S`
- on the same program line (after compiler transformations) if there's a `<: Any`
- and on the same program if there's a `>: Nothing`

Note that not only the checks for bounds are made on Strings. They also pertain the whole line of the code, not necessarily the same type as in question.
Also I bet they would trigger for things like `println("<: Any")` on the same line.
