### ISSUE TITLE
1.4.9 release failed

### ISSUE THREAD

**Issue by mccartney** [scapegoat-scala/scapegoat#537]
I've triggered the 1.4.9 release yesterday, but the artifacts don't seem to be visible.

cc #520 #527

**Comment by mccartney** [comment]
https://github.com/sksamuel/scapegoat/actions/runs/942367182 which is the `v1.4.9` run of the "Release" workflow ended up with a failure:
```
The workflow is not valid. .github/workflows/master-release.yml (Line: 9, Col: 9): Unexpected symbol: '‘sksamuel/scapegoat’'. Located at position 22 within expression: github.repository == ‘sksamuel/scapegoat’
```

**Comment by mccartney** [comment]
Seems like https://github.com/sksamuel/scapegoat/pull/492/commits/55779c0e4d8ff5758a43deb603bf97081c924df4 is the culprit (#492)

**Comment by mccartney** [comment]
Manually moving the tag:
```
➜  scapegoat git:(master) git tag -f v1.4.9
Updated tag 'v1.4.9' (was 67713e5)
```

**Comment by mccartney** [comment]
Seems that now the workflow has picked up the changes. Will check in a few hours. cc @arixmkii

**Comment by arixmkii** [comment]
Works now. Builds are successful.

@mccartney thank you for solving this quickly!
