### ISSUE TITLE
Move to org

### ISSUE THREAD

**Issue by sksamuel** [scapegoat-scala/scapegoat#546]
@mccartney What do you think about moving scapegoat to a top level github org ?

**Comment by mccartney** [comment]
No objections here. Just two thoughts:

1. If we did that, we could optionally also consider changing the Maven artifact id.
2. And then as a consequence, it'd require us to submit a ticket to OSS Nexus for new publishing rights for new artifacts.

**Comment by sksamuel** [comment]
If we want to change the groupIds for maven then we could bump to 2.0.
I don't mind either way - com.sksamuel keeps it consistent with what's there before but if you want to drop my name from it to reflect the org that's fine by me too.

**Comment by sksamuel** [comment]
https://github.com/scapegoat-scala

**Comment by eugene-sy** [comment]
Shall we move the gradle plugin to the org as well?

**Comment by sksamuel** [comment]
You're the owner of the plugin right ?
https://github.com/eugene-sy/gradle-scapegoat-plugin

If you want to move the project in, and you become a member of this org, that's absolutely fine by me.

**Comment by eugene-sy** [comment]
Yes, I am the owner. 
I think it makes sense to keep all the parts of the 'ecosystem' in one place. 
I cannot transfer the project, it requires permission to create repositories in the org. So, I guess membership should be first.

**Comment by sksamuel** [comment]
You are now invited.

**Comment by sksamuel** [comment]
Check this out @eugene-sy @mccartney https://github.com/scapegoat-scala/scapegoat/issues/567
