### ISSUE TITLE
Provide builds compatible with Scala 2.12.15

### ISSUE THREAD

**Issue by arixmkii** [scapegoat-scala/scapegoat#560]
Scala 2.12.15 is available now. As scapegoat uses CrossFull builds, a new version is needed to be built either with the same release number (but as the values come in source, not from external resources, probably not) or a new version release should be published.

There are some subtle changes with this release (in addition to new JDK support) https://github.com/scala/scala/releases/tag/v2.12.15 Don't know if it requires code changes on scapegoat side.

**Comment by will-sargent-eero** [comment]
I think the scala-steward fix is incorrect https://github.com/scapegoat-scala/scapegoat/commit/01620be9fa517a0e5f5216bced520b7abd2337ee#r56671697

**Comment by mccartney** [comment]
Release of [1.4.10](https://github.com/scapegoat-scala/scapegoat/releases/tag/v1.4.10) with support for 2.12.15 has just been initiated. Should be available soon.

**Comment by mccartney** [comment]
I can see 1.14.10 with 2.12.15 build is available in Maven.
