### ISSUE TITLE
Support for 2.13.8

### ISSUE THREAD

**Issue by will-sargent-eero** [scapegoat-scala/scapegoat#635]
Using scalafix and scapegoat on the same project can cause issues because `scalafixEnable` likes to reset the version of scalaVersion to `2.13.8`, and there isn't a scapegoat version matching that.

https://github.com/scalacenter/scalafix/issues/1573

**Comment by saeltz** [comment]
It's not shown as a release on GitHub but the latest version `1.4.12` supports Scala `2.13.8`: https://github.com/scapegoat-scala/scapegoat/releases/tag/v1.4.12
