### ISSUE TITLE
Support for 2.13.9

### ISSUE THREAD

**Issue by sebastian-peter** [scapegoat-scala/scapegoat#679]
Support for scala 2.13.9 would be wonderful at some point in time.

**Comment by henricook** [comment]
I've raised https://github.com/scapegoat-scala/scapegoat/pull/680 but it's the first time I've contributed to this project and I can't then do releases so hopefully the merge gods look soon 🙏🏻

**Comment by mccartney** [comment]
Thank you @henricook for the contribution.

I've just triggered the release of 1.4.16 with this. Ping me here if it it doesn't work for you.
