### ISSUE TITLE
please compile for scala 2.13.11

### ISSUE THREAD

**Issue by domdorn** [scapegoat-scala/scapegoat#748]
2.13.11 is already on maven central
https://contributors.scala-lang.org/t/scala-2-13-11-release-planning/6088/11

**Comment by domdorn** [comment]
nevermind, seems to work with 2.1.0

**Comment by saeltz** [comment]
Support was added in https://github.com/scapegoat-scala/scapegoat/pull/746. @mccartney would need to release a new version.

**Comment by domdorn** [comment]
thanks @saeltz and @mccartney! just fetched and everything works perfectly!
