### ISSUE TITLE
Support Gitlab / Clodeclimate report format

### ISSUE THREAD

**Issue by gaeljw** [scapegoat-scala/scapegoat#775]
Hello folks,

I'm totally new to the project. I was looking to see if it could be used on a Gitlab CI context with integration with Gitlab Merge Requests.

To do so, the plugin would have to generate a report in a specific format.

See https://docs.gitlab.com/ee/ci/testing/code_quality.html#implement-a-custom-tool

> Example:
> ```json
> [
>   {
>     "description": "'unused' is assigned a value but never used.",
>     "check_name": "no-unused-vars",
>     "fingerprint": "7815696ecbf1c96e6894b779456d330e",
>     "severity": "minor",
>     "location": {
>       "path": "lib/index.js",
>       "lines": {
>         "begin": 42
>       }
>     }
>   }
> ]
> ```

Do you think this would technically be feasible? If yes, would you be open for a PR to support this?

Thanks,

**Comment by Johnnei** [comment]
Technically this is definitely possible. At my work we translate the generated scalastyle xml into the Code Quality format.

There are a few pain points though:
- GitLab (atleast 15) supports only a single file, so the build tool needs to do report aggregation
- As the format is json, we need to decide whether we'll bundle a json lib or do some silly templating to avoid dependency conflicts in the builds.

**Comment by saeltz** [comment]
Scapegoat already exports reports as scalastyle/checkstyle XML. That could be used as inspiration or starting point as @Johnnei pointed out.

Feel free to open a PR that we can take a look at.

**Comment by gaeljw** [comment]
Thanks for the feedback. I'll be happy to provide a PR if my company goes in this direction (Gitlab Code Quality + Scapegoat). I mean I probably won't provide a PR in the next days, more a matter of weeks/months :)
