### ISSUE TITLE
SwallowedException when exception is logged and custom exception is rethrown

### ISSUE THREAD

**Issue by uhla** [scapegoat-scala/scapegoat#842]
If you take the following snippet, I get SwallowedException, even though I have logged the message before throwing my custom message in another exception, I don't want to include it in the WebAppException, because I don't want to expose the inside structure of my app to somebody calling this externally (imagine that on endpoint).

Is this considered a false positive or is there a chance this kind of behavior (i.e. logging) could be detected and considered as handling?

Sonar for example has rule LogOrRethrow for cases like this.

```
import org.slf4j.LoggerFactory

import javax.ws.rs.WebApplicationException
import javax.ws.rs.core.Response.Status

class MyClass {
  val log = LoggerFactory.getLogger(getClass)

  def myMethodWithTryCatch(): Unit = {
    try {
      throw new IllegalArgumentException("something")
    } catch {
      case e: IllegalArgumentException =>
        log.warn("Whops! Still log it, though", e)
        throw new WebApplicationException("MyCustomMessage", Status.BAD_REQUEST)
    }
  }
}
```

```
[scapegoat] [SwallowedException] Empty catch block
  If you use a try/catch block to deal with an exception, you should handle all of the caught exceptions and if for some reason you're throwing another exception in the result, you should include the original exception as the cause.
  case (e @ (_: IllegalArgumentException)) => {
  MyClass.this.log.warn(e.getMessage(), e);
  throw 

      case e: IllegalArgumentException =>
```

**Comment by saeltz** [comment]
I think scapegoat's description already gives the answer:

> If you use a try/catch block to deal with an exception,... and if for some reason you're throwing another exception in the result, you should include the original exception as the cause.

You're not including the original exception as the cause. It has nothing to do with the logging.
