### ISSUE TITLE
Run sbt ci-release failure

### ISSUE THREAD

**Issue by mccartney** [scapegoat-scala/scapegoat#851]
Context:
https://github.com/scapegoat-scala/scapegoat/pull/848#issuecomment-2188766917

Symptoms:
https://github.com/scapegoat-scala/scapegoat/actions/runs/9525951458/job/26637201869 has failed with:
```
[warn] Ignored unknown package option FixedTimestamp(Some(1262304000000))
[info] Wrote /home/runner/work/scapegoat/scapegoat/target/scala-2.12.18/scalac-scapegoat-plugin_2.12.18-2.1.6+5-d67c7737-SNAPSHOT.pom
[error] java.net.ProtocolException: Server redirected too many  times (20)
[error] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[error] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[error] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[error] 	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1952)
[error] 	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:19[47](https://github.com/scapegoat-scala/scapegoat/actions/runs/9525951458/job/26637201869#step:8:48))
[error] 	at java.security.AccessController.doPrivileged(Native Method)
[error] 	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1946)
[error] 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1516)
[error] 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1500)
[error] 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
[error] 	at org.apache.ivy.util.url.BasicURLHandler.upload(BasicURLHandler.java:288)

... redacted for brevity
```

FYI @saeltz

**Comment by mccartney** [comment]
https://github.com/sbt/sbt-pgp/issues/182#issuecomment-727572511 hints that this is a Sonatype credential issue.

Which reminds me of my recent problems with releasing an unrelated Maven/Java package. And there it turned out I should no longer use my username + password as credentials to Sonatype, but I should rather generate an Access Token (long-lived).

Therefore:
@sksamuel could you please:
1. login to https://oss.sonatype.org/
1. Go to Profile
1. Pull down User Token
1. Access User Token
1. Put these credentials into secrets in this Github repo?

(Likely you will need to do the same for other repos of yours)

**Comment by saeltz** [comment]
@sksamuel, quick reminder that this blocks us from releasing.

**Comment by saeltz** [comment]
@sksamuel, ping.

**Comment by Johnnei** [comment]
Probably unsurprisingly, running into this for the sbt plugin as well:  https://github.com/scapegoat-scala/sbt-scapegoat/actions/runs/9882941292/job/27296750946

**Comment by mccartney** [comment]
An alternative would probably be to set up a new Sonatype/Maven identity - i.e. new artifacts group/id and discontinue the `sksamuel` branding. But I wouldn't want to do that without involving Sam.
(the Github org has already shifted some time ago)

**Comment by Johnnei** [comment]
@sksamuel Any chance you could help us out here?

**Comment by Johnnei** [comment]
@sksamuel Could you help unblock us here?

**Comment by sksamuel** [comment]
sorry I don't know why I didn't spot this earlier despite the pings.
Let me fix now.

**Comment by sksamuel** [comment]
I wonder if github emails weren't working, don't see anything in my inbox.

**Comment by sksamuel** [comment]
Ok this release has gone out: https://github.com/scapegoat-scala/scapegoat/actions/runs/10155857170

**Comment by sksamuel** [comment]
I updated sbt-scapegoat too, but it seems there's another error on that one: https://github.com/scapegoat-scala/sbt-scapegoat/actions/runs/9882941292/job/28083347983

**Comment by Johnnei** [comment]
> I updated sbt-scapegoat too, but it seems there's another error on that one: https://github.com/scapegoat-scala/sbt-scapegoat/actions/runs/9882941292/job/28083347983

Hmm, even after a minor change it still fails. I'll dig into this on my evening. Symptom looks same that it might still be using the old token though, but logs are slightly different from here 🤔

**Comment by Johnnei** [comment]
Fixed sbt-scapegoat by removing the override to the old oss server: https://github.com/scapegoat-scala/sbt-scapegoat/actions/runs/10164408323/job/28109675970

Thanks a lot!
